### ISSUE TITLE
Release win x64 pls

### ISSUE THREAD

**Issue by Be1zebub** [wyozi/g-ace-io#9]
Release win x64 pls
thx u **<3**

**Comment by wyozi** [comment]
I'm not actively maintaining this. Do you need it for g-ace or something else?

**Comment by Be1zebub** [comment]
yes, for g-ace.

**Comment by wyozi** [comment]
It's gonna be easier for you to figure out how to compile it yourself. I'm not using windows atm

**Comment by Be1zebub** [comment]
ok :(
